import '@/lib/env';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import './globals.css';
import { Toaster } from 'sonner';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Cloudtruck Admin Dashboard',
  description: 'Staff operations dashboard for Cloudtruck managed trucking system',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the nonce generated by middleware so Next.js uses it for its own
  // injected inline scripts, satisfying the nonce-based Content-Security-Policy.
  const nonce = (await headers()).get('x-nonce') ?? undefined;

  return (
    <html lang="en" nonce={nonce}>
      <body className={`${inter.variable} font-sans antialiased`}>
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
